apiVersion: v1
kind: Namespace
metadata:
  name: services
  labels:
    name: services
    environment: dev

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: services
  labels:
    app: user-service
spec:
  replicas: 2   # Two pods for high availability

  selector:
    matchLabels:
      app: order-service   # Must match pod template labels

  template:
    metadata:
      labels:
        app: order-service

    spec:
      containers:
        - name: order-service
          image: IMAGE_PLACEHOLDER

          imagePullPolicy: IfNotPresent
          # Since image is locally imported into k3d

          ports:
            - containerPort: 8080
              name: http

          # Basic health checks (very important in real systems)
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: services
spec:
  type: ClusterIP   # Internal only

  selector:
    app: order-service

  ports:
    - port: 8080          # Service port
      targetPort: 8080    # Container port
      protocol: TCP
      name: http